# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0609eccd26a0fcd3282956afe9ec1b9938d239b4f78c463bd255a15cc599f4ec1c7f46e6e758e6b9690d5480a20f5e81896905a91a55d697c1b0d92504f85692

test:
  secret_key_base: bca8703f8795c83ebd02d6a5980c4b55ffcc878eb2e5803aee5fa9a7230e5dd96cf333fe4430fd4c8905a01aeb2311015893d6a01db91439384582cbe75c4606

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
